config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'

  Rails.application.config.default_locales.each do |locale|
    get "welcome/index_#{locale[0].to_s}" => redirect("/welcome?locale=#{locale[1]}")
  end

  get 'rules' => 'rules#index'

  get 'informations' => 'informations#index'

  get 'calendar' => 'calendar#index'
  get 'calendar_for_iframe' => 'calendar#show'

  get 'character_skins' => 'character_skins#show'

  post 'contact' => 'contact#contact'

  get 'donations' => 'donations#index'
  post 'donation' => 'donations#donation'

  get 'rankings' => 'rankings#index'

  get 'streams' => 'streams#index'

  get 'statistics' => 'statistics#index'

  get 'tos' => 'tos#index'

  get 'videos' => 'videos#index'

  # DE routes:
  get 'communities' => 'communities#index'
  get 'communities/nrw' => 'communities#nrw'
  get 'communities/hessen' => 'communities#hessen'
  get 'communities/nds' => 'communities#nds'
  get 'communities/bayern' => 'communities#bayern'
  get 'communities/berlin' => 'communities#berlin'
  get 'communities/norden' => 'communities#norden'
  get 'communities/osten' => 'communities#osten'
  get 'communities/bawu' => 'communities#bawu'

  # FR & IT routes:
  get "/communities/regions/:name" => "communities#regions"
  get "/communities/character_discords" => "communities#character_discords"
  resources :communities

  # PT routes:
  get 'locus_league' => 'locus_league#index'

  resources :teams
  post 'teams/add_player/:id' => 'teams#add_player'
  post 'teams/remove_player/:id' => 'teams#remove_player'

  resources :news
  resources :feedbacks
  # get 'administrators' => 'administrators#index'
  get 'imprint' => 'imprint#index'
  get 'privacy_policy' => 'privacy_policy#index'

  resources :tournaments
  post 'tournaments/add_player/:id' => 'tournaments#add_player'
  post 'tournaments/remove_player/:id' => 'tournaments#remove_player'
  post 'tournaments/setup/:id' => 'tournaments#setup'
  post 'tournaments/start/:id' => 'tournaments#start'
  post 'tournaments/finish/:id' => 'tournaments#finish'
  post 'tournaments/cancel/:id' => 'tournaments#cancel'
  patch 'tournaments/sort_players/:id' => 'tournaments#sort_players'
  patch 'tournaments/seed_players/:id' => 'tournaments#seed_players'

  get 'players/unregistered' => 'players#unregistered'
  post 'players/export/:id' => 'players#export'
  resources :players, except: [:new]

  resources :registrations, only: [:update]

  resources :survey_responses, only: [:create, :update]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index, :update, :destroy]

  mount Thredded::Engine => '/thredded'
  get 'forum' => 'forum#index'

  namespace :shop do
    resource :shopping_cart, only: [:show, :destroy]
    get 'checkout', to: 'orders#new', as: 'checkout'
    resources :orders, only: [:index, :show, :edit, :create, :update, :destroy] # :new -> checkout
    resources :seller_orders, only: [:index, :show, :update]
    patch 'products/:id/move_down', to: 'products#move_down', as: 'product_move_down'
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :purchases, only: [:index, :create, :update, :destroy]
    namespace :stripe do
      get 'checkout', to: 'checkouts#checkout'
      get 'checkout_success', to: 'checkouts#success'
      get 'checkout_cancel', to: 'checkouts#cancel'
      post 'webhook', to: 'webhooks#webhook'
      get 'account_link', to: 'accounts#account_link'
      get 'account_return', to: 'accounts#return'
      get 'account_refresh', to: 'accounts#refresh'
    end
  end
  get 'shop', to: 'shop#index'

  root to: "welcome#index"

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  require 'will_paginate/array'

  before_action { @section = 'rankings' }

  # GET /rankings
  # GET /rankings.json
  def index
    @players = Player.all_from(session['country_code'])
    # @players_2020 = Player.all_from(session['country_code']).includes(:user).includes(:results).where("results.created_at >= ?", Time.zone.local(2020,1,1)).references(:results)
    # @players_2019 = Player.all_from(session['country_code']).includes(:user).includes(:results).where("results.created_at >= ?", Time.zone.local(2019,1,1)).references(:results)
    if params[:filter].nil? or params[:filter] == 'all'
      @players = @players.where('participations >= 3').sort_by do |p|
        [p.points.to_f/p.participations, p.participations, -p.created_at.to_i]
      end.reverse.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
      # @players_2019 = @players_2019.where('participations >= 3').sort_by do |p|
      #   [p.points.to_f/p.participations, p.participations, -p.created_at.to_i]
      # end.reverse.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
    elsif params[:filter] == 'participations'
      @players = @players.where('participations > 0').order(participations: :desc, points: :desc, created_at: :asc).paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
      # @players_2019 = @players_2019.where('participations > 0').order(participations: :desc, points: :desc, created_at: :asc).paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
    elsif params[:filter] == 'seed_points'
      @players = helpers.seed_players(@players).paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
      # @players_2019 = helpers.seed_players(@players_2019).paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
    elsif params[:filter] == 'major' && params[:major].present?
      @players = @players.where('participations > 0').includes(:results).where("results.major_name ILIKE ?", "%#{ActiveRecord::Base.sanitize_sql_like(params[:major])}%").references(:results).sort_by do |p|
        p.results_sum(params[:major]) << -p.created_at.to_i
      end.reverse.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
      # @players_2019 = @players_2019.where('participations > 0').includes(:results).where("results.major_name ILIKE ?", "%#{ActiveRecord::Base.sanitize_sql_like(params[:major])}%").references(:results).sort_by do |p|
      #   p.results_sum(params[:major]) << -p.created_at.to_i
      # end.reverse.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
    elsif helpers.tournament_cities_with_a_weekly.include?(params[:filter].capitalize)
      city = params[:filter].capitalize
      @players = @players.where('participations > 0').includes(:results).where(results: {city: city}).sort_by do |p|
        p.results_sum(city) << -p.created_at.to_i
      end.reverse.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
      # @players_2019 = @players_2019.where('participations > 0').includes(:results).where(results: {city: city}).sort_by do |p|
      #   p.results_sum(city) << -p.created_at.to_i
      # end.reverse.paginate(page: params[:page], per_page: Player::MAX_PLAYERS_PER_PAGE)
    end
    render "index_#{session['country_code']}"
  end

end

app/views/rankings/_paginator.html.haml
- if players.any? && players.try(:total_pages).present?
  %nav
    %ul.pagination
      %li= hidden_field_tag 'total_pages', players.total_pages
      %li.left-arrow
        - if players.current_page.present? && players.current_page > 1
          = link_to rankings_path(filter: params[:filter], major: params[:major], page: players.current_page-1, anchor: anchor), aria: {label: "Previous"} do
            %span{"aria-hidden"=> "true"}
              &laquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &laquo;

      - (1..players.total_pages).each do |page|
        %li{class: "#{"active" if page == players.current_page}"}= link_to page.to_s, rankings_path(filter: params[:filter], major: params[:major], page: page, anchor: anchor), value: page
      %li.right-arrow
        - if players.try(:current_page).present? && players.current_page < players.total_pages
          = link_to rankings_path(filter: params[:filter], major: params[:major], page: players.current_page+1, anchor: anchor), aria: {label: "Next"} do
            %span{"aria-hidden"=> "true"}
              &raquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &raquo;

app/views/rankings/_points_ch.html.haml
.rankings__filter
  .row.without_col
    .rankings__filter__button= link_to t('rankings.filter.overall'), rankings_path(filter: 'all', anchor: 'points'), class: "btn #{(params[:filter].nil? or params[:filter] == 'all') ? 'btn-sstm' : 'btn-ghost'}"
    .rankings__filter__button= link_to t('rankings.filter.seed_points'), rankings_path(filter: 'seed_points', anchor: 'points'), class: "btn #{(params[:filter] == 'seed_points') ? 'btn-sstm' : 'btn-ghost'}"
    .rankings__filter__button= link_to t('players.participations'), rankings_path(filter: 'participations', anchor: 'points'), class: "btn #{(params[:filter] == 'participations') ? 'btn-sstm' : 'btn-ghost'}"
  .row.without_col
    - tournament_majors.each do |major|
      .rankings__filter__button= link_to major, rankings_path(filter: 'major', anchor: 'points', major: major), class: "btn #{(params[:filter] == 'major' and params[:major] == major) ? 'btn-sstm' : 'btn-ghost'}"
  .row.without_col
    - tournament_cities_with_a_weekly.each do |city|
      .rankings__filter__button= link_to "Weekly #{city}", rankings_path(filter: city.downcase, anchor: 'points'), class: "btn #{params[:filter] == city.downcase ? 'btn-sstm' : 'btn-ghost'}"
  .row
    .col{style: 'font-size: 12px;'}
      = t('rankings.filter.note')

%table.table.table-hover.table-borderless
  %thead.table-header
    %tr
      %th.text-center #
      %th.text-center
        - if params[:filter] == 'participations'
          = t('players.participations')
        - else
          = t('players.points')
      %th= t('players.gamer_tag')
      %th.text-center= t('players.mains')
      %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
        - if params[:filter] == 'participations'
          = t('players.points')
        - else
          = t('players.participations')
      %th.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= t('w_l')

  %tbody.table-content.with-show
    - if players.any?
      - last_player_points = nil
      - page_multiplicator = Player::MAX_PLAYERS_PER_PAGE*params[:page].to_i
      - page_multiplicator -= Player::MAX_PLAYERS_PER_PAGE if params[:page].to_i != 0
      - players.each_with_index do |player, i|
        - if (params[:filter].nil? or params[:filter] == 'all' or params[:filter] == 'participations' or params[:filter] == 'seed_points')
          - if params[:filter] == 'participations'
            - points = player.participations
          - elsif params[:filter] == 'seed_points'
            - points = player.seed_points.round(2)
          - else
            - points = (player.points.to_f/player.participations).round(2)
          - if params[:filter] == 'participations'
            - participations = player.points
          - else
            - participations = player.participations
          - if player.wins == 0 and player.losses == 0
            - win_loss_ratio = nil
          - else
            - win_loss_ratio = player.win_loss_ratio
        - else
          - results_sum = player.results_sum(params[:major] || params[:filter])
          - points = results_sum[0]
          - participations = -results_sum[1]
          - win_loss_ratio = results_sum[2]
        - if participations > 0 or params[:filter] == 'seed_points'
          %tr{'data-id': player.id, 'data-component'=>'player'}
            %td.text-center= (last_player_points == points) ? '' : (page_multiplicator+i+1).ordinalize
            %td.text-center= points
            - last_player_points = points
            %td= player.prefix.present? ? "#{player.prefix} | #{player.gamer_tag}" : player.gamer_tag
            %td.text-center
              - if player.main_characters.any?
                %div
                  - player.main_characters[0...3].each do |char|
                    - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
                      = image_tag "characters/#{char}.png", height: '25px', width: '25px'
            %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell= participations
            %td.text-center.d-sm-table-cell.d-none.d-md-table-cell.d-lg-none.d-xl-table-cell
              = win_loss_ratio.nil? ? '-' : "#{win_loss_ratio} %"

            - if current_user.present? and current_user.super_admin?
              %td.admin-list-actions
                .admin-list-actions__link
                  = link_to edit_player_path(player), class:'btn btn-ghost btn-square' do
                    %span.material-icons.admin-actions__link__icon= 'edit'

                .admin-list-actions__link
                  = link_to player, method: :delete, data: { confirm: t('confirm') }, class: 'btn btn-sstm btn-square' do
                    %span.material-icons.admin-actions__link__icon= 'delete'

.ranking-list-footer
  = render 'paginator', players: players, anchor: 'points'

- if !players.any?
  %p{style: 'text-align: center;'}
    = t('rankings.no_players_found')

app/views/rankings/_s1_19_de.html.haml
= link_to asset_url('rankings/pr_s1_19_de.jpg') do
  = image_tag "rankings/pr_s1_19_de.jpg", width: '100%'

app/views/rankings/_s1_20_ch.html.haml
%p{style: 'text-align: center;'}
  = t('rankings.s1_20.no_ranking')

app/views/rankings/_s1_20_de.html.haml
= link_to asset_url('rankings/pr_s1_20_de.jpg') do
  = image_tag "rankings/pr_s1_20_de.jpg", width: '100%'

app/views/rankings/_s1_21_ch.html.haml
%p{style: 'text-align: center;'}
  = t('rankings.s1_21.no_ranking')

app/views/rankings/_s1_22_de.html.haml
%p{style: 'text-align: center;'}
  = t('rankings.s1_22.no_ranking')

app/views/rankings/_s2_19_ch.html.haml
= link_to asset_url('rankings/pr_s2_19_ch.jpg') do
  = image_tag "rankings/pr_s2_19_ch.jpg", width: '100%'
%br
%br
%h2= t('rankings.s2_19.top15')
%table.table.table-hover.table-borderless
  %thead.table-header
    %tr
      %th.text-center #
      %th= t('players.gamer_tag')
      %th.text-center= t('players.mains')
      %th.text-center.d-sm-table-cell.d-none.d-md-table-cell.d-lg-none.d-xl-table-cell= t('players.participations')
      %th.text-center.d-sm-table-cell.d-none.d-md-table-cell.d-lg-none.d-xl-table-cell= t('w_l')

  %tbody.table-content.with-show
    %tr{'data-id': 240, 'data-component'=>'player'}
      %td.text-center= 1.ordinalize
      %td= 'mYi | Destany'
      %td.text-center
        %div
          - ['meta_knight', 'wolf'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 29, 'data-component'=>'player'}
      %td.text-center= 2.ordinalize
      %td= 'SoS | Karpador64'
      %td.text-center
        %div
          - ['luigi'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 267, 'data-component'=>'player'}
      %td.text-center= 3.ordinalize
      %td= 'BG | Crash'
      %td.text-center
        %div
          - ['wii_fit_trainer', 'bowser'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 85, 'data-component'=>'player'}
      %td.text-center= 4.ordinalize
      %td= 'SIR | Phonky'
      %td.text-center
        %div
          - ['pac_man'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 253, 'data-component'=>'player'}
      %td.text-center= 5.ordinalize
      %td= 'SLNT | DeepFreeze'
      %td.text-center
        %div
          - ['falco', 'fox'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 233, 'data-component'=>'player'}
      %td.text-center= 6.ordinalize
      %td= 'WOR | Olivia'
      %td.text-center
        %div
          - ['duck_hunt', 'rob'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 262, 'data-component'=>'player'}
      %td.text-center= 7.ordinalize
      %td= 'SLNT | Kepler'
      %td.text-center
        %div
          - ['snake'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 149, 'data-component'=>'player'}
      %td.text-center= 8.ordinalize
      %td= 'Sickboy'
      %td.text-center
        %div
          - ['pikachu', 'wolf', 'rob'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 88, 'data-component'=>'player'}
      %td.text-center= 9.ordinalize
      %td= 'SIR | Jaka'
      %td.text-center
        %div
          - ['isabelle'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 43, 'data-component'=>'player'}
      %td.text-center= 10.ordinalize
      %td= 'BG | ItseMePG'
      %td.text-center
        %div
          - ['snake'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 254, 'data-component'=>'player'}
      %td.text-center= 11.ordinalize
      %td= 'AG | Benji'
      %td.text-center
        %div
          - ['wario'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 48, 'data-component'=>'player'}
      %td.text-center= 12.ordinalize
      %td= 'Purist'
      %td.text-center
        %div
          - ['chrom', 'snake'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 147, 'data-component'=>'player'}
      %td.text-center= 13.ordinalize
      %td= 'eLS | Acsor'
      %td.text-center
        %div
          - ['inkling'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 52, 'data-component'=>'player'}
      %td.text-center= 14.ordinalize
      %td= 'Rampage'
      %td.text-center
        %div
          - ['zero_suit_samus'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %
    %tr{'data-id': 141, 'data-component'=>'player'}
      %td.text-center= 15.ordinalize
      %td= 'SGE | Yannwatts'
      %td.text-center
        %div
          - ['ness'].each do |char|
            - if File.file?("#{Rails.root}/app/assets/images/characters/#{char}.png")
              = image_tag "characters/#{char}.png", height: '25px', width: '25px'
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell
      %td.text-center.d-none.d-sm-table-cell.d-md-table-cell.d-lg-none.d-xl-table-cell  %

%h2= t('rankings.s2_19.counted_tournaments')
%ul
  %li (S) SSBU - BLICK ESPORTS MASTERS CUP #6
  %li (S) SSBU - BLICK ESPORTS MASTERS CUP #5
  %li (S) SSBU - BLICK ESPORTS MASTERS CUP #4
  %li (S) SSBU - BLICK ESPORTS MASTERS CUP #3
  %li (A) Exodus 2
  %li (B) Smash Castle : Diamond Kingdom Tournament
  %li (B) Saint Smash #2
  %li (B) SoluSmash 5/6 - Saison 1
  %li (B) PK Bern #7
  %li (B) SoluSmash 4/6 - Saison 1
  %li (B) Orcus Smash #1
  %li (B) Gamesession XIII (SNWC Major)
  %li (B) UltiMon 5
  %li (B) PK Bern #4
  %li (B) Carrefour Sud x E-lvets #2
  %li (C) SNWC Finals 2019
  %li (C) Super Smash Qwertz #3
  %li (C) Orcus Smash #2
  %li (C) Xano
  %li (C) SSBU - BLICK ESPORTS MASTERS CUP GRAND FINAL
  %li (C) Colosseum Basel XIII
  %li (C) Servette Smash Tournament
  %li (C) Super Smash Qwertz
  %li (C) SoluSmash 3/6 - Saison 1
  %li (C) PK Bern #5
  %li (C) SoluSmash2 (UTSR2) - Saison1, Tournoi2
  %li (C) PK Bern #3
  %li (C) Casino - Let&#039;s Play 2
  %li (C) Ultimate Tournament Suisse Romande 1/6
  %br
  S Tier (64) / A Tier (48) / B Tier (32) / C Tier (16)

%h2= t('rankings.s2_19.considered_tournaments')
%ul
  %li NeS-Fnac #4 (Seeding)
  %li UltiMelt #17 (No URL to be found)
  %li PK Bern #6 (Seeding)
  %li Ultimon 6 (Not announced in time)
  %li Pubtendo 1Pub 1Up - Turnier (No URL to be found)
  %li Ultimon #7 (Not announced in time)
  %li Gamecity 2.0 (Not announced in time)
  %li Super Tech Smash #2 - Fall 2019 (Seeding)
  %li Super Smash Qwertz (Seeding)
  %li HeroFest 2019 (Seeding)
  %li PK Bern #8 (Seeding)

app/views/rankings/_s2_19_de.html.haml
= link_to asset_url('rankings/pr_s2_19_de.jpg') do
  = image_tag "rankings/pr_s2_19_de.jpg", width: '100%'