config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'

  Rails.application.config.default_locales.each do |locale|
    get "welcome/index_#{locale[0].to_s}" => redirect("/welcome?locale=#{locale[1]}")
  end

  get 'rules' => 'rules#index'

  get 'informations' => 'informations#index'

  get 'calendar' => 'calendar#index'
  get 'calendar_for_iframe' => 'calendar#show'

  get 'character_skins' => 'character_skins#show'

  post 'contact' => 'contact#contact'

  get 'donations' => 'donations#index'
  post 'donation' => 'donations#donation'

  get 'rankings' => 'rankings#index'

  get 'streams' => 'streams#index'

  get 'statistics' => 'statistics#index'

  get 'tos' => 'tos#index'

  get 'videos' => 'videos#index'

  # DE routes:
  get 'communities' => 'communities#index'
  get 'communities/nrw' => 'communities#nrw'
  get 'communities/hessen' => 'communities#hessen'
  get 'communities/nds' => 'communities#nds'
  get 'communities/bayern' => 'communities#bayern'
  get 'communities/berlin' => 'communities#berlin'
  get 'communities/norden' => 'communities#norden'
  get 'communities/osten' => 'communities#osten'
  get 'communities/bawu' => 'communities#bawu'

  # FR & IT routes:
  get "/communities/regions/:name" => "communities#regions"
  get "/communities/character_discords" => "communities#character_discords"
  resources :communities

  # PT routes:
  get 'locus_league' => 'locus_league#index'

  resources :teams
  post 'teams/add_player/:id' => 'teams#add_player'
  post 'teams/remove_player/:id' => 'teams#remove_player'

  resources :news
  resources :feedbacks
  # get 'administrators' => 'administrators#index'
  get 'imprint' => 'imprint#index'
  get 'privacy_policy' => 'privacy_policy#index'

  resources :tournaments
  post 'tournaments/add_player/:id' => 'tournaments#add_player'
  post 'tournaments/remove_player/:id' => 'tournaments#remove_player'
  post 'tournaments/setup/:id' => 'tournaments#setup'
  post 'tournaments/start/:id' => 'tournaments#start'
  post 'tournaments/finish/:id' => 'tournaments#finish'
  post 'tournaments/cancel/:id' => 'tournaments#cancel'
  patch 'tournaments/sort_players/:id' => 'tournaments#sort_players'
  patch 'tournaments/seed_players/:id' => 'tournaments#seed_players'

  get 'players/unregistered' => 'players#unregistered'
  post 'players/export/:id' => 'players#export'
  resources :players, except: [:new]

  resources :registrations, only: [:update]

  resources :survey_responses, only: [:create, :update]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index, :update, :destroy]

  mount Thredded::Engine => '/thredded'
  get 'forum' => 'forum#index'

  namespace :shop do
    resource :shopping_cart, only: [:show, :destroy]
    get 'checkout', to: 'orders#new', as: 'checkout'
    resources :orders, only: [:index, :show, :edit, :create, :update, :destroy] # :new -> checkout
    resources :seller_orders, only: [:index, :show, :update]
    patch 'products/:id/move_down', to: 'products#move_down', as: 'product_move_down'
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :purchases, only: [:index, :create, :update, :destroy]
    namespace :stripe do
      get 'checkout', to: 'checkouts#checkout'
      get 'checkout_success', to: 'checkouts#success'
      get 'checkout_cancel', to: 'checkouts#cancel'
      post 'webhook', to: 'webhooks#webhook'
      get 'account_link', to: 'accounts#account_link'
      get 'account_return', to: 'accounts#return'
      get 'account_refresh', to: 'accounts#refresh'
    end
  end
  get 'shop', to: 'shop#index'

  root to: "welcome#index"

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action { @section = 'videos' }

  # GET /videos
  # GET /videos.json
  def index
    @players = Player.all_from(session['country_code']).where("youtube_video_ids <> '' is true").order(updated_at: :desc).paginate(page: params[:page], per_page: Player::MAX_PLAYER_VIDEOS_PER_PAGE)
  end

end

app/views/videos/_paginator.html.haml
- if @players.any? && @players.try(:total_pages).present?
  %nav
    %ul.pagination
      %li= hidden_field_tag 'total_pages', @players.total_pages
      %li.left-arrow
        -# table_params is a helper methode to whitelist the needed params to sort and order
        - if @players.current_page.present? && @players.current_page > 1
          = link_to videos_path(page: @players.current_page-1), aria: {label: "Previous"} do
            %span{"aria-hidden"=> "true"}
              &laquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &laquo;
      - (1..@players.total_pages).each do |page|
        %li{class: "#{"active" if page == @players.current_page}"}= link_to page.to_s, videos_path(page: page), value: page
      %li.right-arrow
        - if @players.try(:current_page).present? && @players.current_page < @players.total_pages
          = link_to videos_path(page: @players.current_page+1), aria: {label: "Next"} do
            %span{"aria-hidden"=> "true"}
              &raquo;
        - else
          %a
            %span{"aria-hidden"=> "true"}
              &raquo;

app/views/videos/index.html.haml
- set_meta_tags description: meta_tag_description('Videos')

.row
  .col
    %h1.page__title= t('video.title2')

.row
  .col
    - @players.each do |player|
      - youtube_video_ids = player.sanitized_youtube_video_ids.split(',')
      .player{style: ('border-top: 1px solid #E5E9EB; margin-top: 1rem; padding-top: 1rem;' if player != @players.first)}
        %h2= t('video.players_videos', player: link_to(player.gamer_tag, player), s: youtube_video_ids.length > 1 ? 's' : '').html_safe
        .player__videos
          .newest_video

            %iframe.newest-video{allow: "autoplay; encrypted-media; picture-in-picture", allowfullscreen: "", frameborder: "0", src: "https://www.youtube-nocookie.com/embed/#{CGI.escape(youtube_video_ids[0])}"}
          - if youtube_video_ids.length > 1
            .other_videos{style: 'margin-top: 1rem;'}
              - require 'open-uri'
              - require 'json'
              - youtube_video_ids[1.. 3].each do |v_id|
                - begin
                  - video_info = JSON.parse(URI.open("https://www.youtube.com/oembed?url=https://youtu.be/#{CGI.escape(v_id)}&format=json").read)
                  .row{style: 'margin-bottom: 1rem;'}
                    .col-4{style: 'text-align: center;'}
                      = link_to image_tag(video_info["thumbnail_url"], width: '100%', alt: 'youtube video thumbnail', style: 'max-width: 220px; max-height: 160px;'), "https://youtu.be/#{v_id}", target: '_blank'
                    .col-8{style: 'margin-top: auto; margin-bottom: auto;'}
                      = link_to video_info["title"], "https://youtu.be/#{v_id}", target: '_blank'
                - rescue => ex
                  %p.hidden
                    %strong= "#{ex}:"
                    = "https://youtu.be/#{v_id}"
.row
  .col
    .videos__pagination
      = render 'paginator'