config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'

  Rails.application.config.default_locales.each do |locale|
    get "welcome/index_#{locale[0].to_s}" => redirect("/welcome?locale=#{locale[1]}")
  end

  get 'rules' => 'rules#index'

  get 'informations' => 'informations#index'

  get 'calendar' => 'calendar#index'
  get 'calendar_for_iframe' => 'calendar#show'

  get 'character_skins' => 'character_skins#show'

  post 'contact' => 'contact#contact'

  get 'donations' => 'donations#index'
  post 'donation' => 'donations#donation'

  get 'rankings' => 'rankings#index'

  get 'streams' => 'streams#index'

  get 'statistics' => 'statistics#index'

  get 'tos' => 'tos#index'

  get 'videos' => 'videos#index'

  # DE routes:
  get 'communities' => 'communities#index'
  get 'communities/nrw' => 'communities#nrw'
  get 'communities/hessen' => 'communities#hessen'
  get 'communities/nds' => 'communities#nds'
  get 'communities/bayern' => 'communities#bayern'
  get 'communities/berlin' => 'communities#berlin'
  get 'communities/norden' => 'communities#norden'
  get 'communities/osten' => 'communities#osten'
  get 'communities/bawu' => 'communities#bawu'

  # FR & IT routes:
  get "/communities/regions/:name" => "communities#regions"
  get "/communities/character_discords" => "communities#character_discords"
  resources :communities

  # PT routes:
  get 'locus_league' => 'locus_league#index'

  resources :teams
  post 'teams/add_player/:id' => 'teams#add_player'
  post 'teams/remove_player/:id' => 'teams#remove_player'

  resources :news
  resources :feedbacks
  # get 'administrators' => 'administrators#index'
  get 'imprint' => 'imprint#index'
  get 'privacy_policy' => 'privacy_policy#index'

  resources :tournaments
  post 'tournaments/add_player/:id' => 'tournaments#add_player'
  post 'tournaments/remove_player/:id' => 'tournaments#remove_player'
  post 'tournaments/setup/:id' => 'tournaments#setup'
  post 'tournaments/start/:id' => 'tournaments#start'
  post 'tournaments/finish/:id' => 'tournaments#finish'
  post 'tournaments/cancel/:id' => 'tournaments#cancel'
  patch 'tournaments/sort_players/:id' => 'tournaments#sort_players'
  patch 'tournaments/seed_players/:id' => 'tournaments#seed_players'

  get 'players/unregistered' => 'players#unregistered'
  post 'players/export/:id' => 'players#export'
  resources :players, except: [:new]

  resources :registrations, only: [:update]

  resources :survey_responses, only: [:create, :update]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index, :update, :destroy]

  mount Thredded::Engine => '/thredded'
  get 'forum' => 'forum#index'

  namespace :shop do
    resource :shopping_cart, only: [:show, :destroy]
    get 'checkout', to: 'orders#new', as: 'checkout'
    resources :orders, only: [:index, :show, :edit, :create, :update, :destroy] # :new -> checkout
    resources :seller_orders, only: [:index, :show, :update]
    patch 'products/:id/move_down', to: 'products#move_down', as: 'product_move_down'
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :purchases, only: [:index, :create, :update, :destroy]
    namespace :stripe do
      get 'checkout', to: 'checkouts#checkout'
      get 'checkout_success', to: 'checkouts#success'
      get 'checkout_cancel', to: 'checkouts#cancel'
      post 'webhook', to: 'webhooks#webhook'
      get 'account_link', to: 'accounts#account_link'
      get 'account_return', to: 'accounts#return'
      get 'account_refresh', to: 'accounts#refresh'
    end
  end
  get 'shop', to: 'shop#index'

  root to: "welcome#index"

end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action { @section = 'informations' }

  # GET /informations
  # GET /informations.json
  def index
    render "index_#{session['country_code']}"
  end

end

app/views/informations/index_ch.html.haml
- set_meta_tags description: meta_tag_description('Information')

.row
  .col
    %h1.page__title= t('information.ch.title')

%ul#information-tabs.nav.nav-pills.nav-fill{role: 'tablist'}
  %li.nav-item
    %a#general-tab.nav-link.active{'data-toggle'=>'tab', href: '#general', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.general.title')
  %li.nav-item
    %a#calendar-tab.nav-link{'data-toggle'=>'tab', href: '#calendar', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.calendar.title')
  %li.nav-item
    %a#power-ranking-tab.nav-link{'data-toggle'=>'tab', href: '#power-ranking', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.power_ranking.title')
  %li.nav-item
    %a#tournament-manager-tab.nav-link{'data-toggle'=>'tab', href: '#tournament-manager', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.tournament_manager.title')
  %li.nav-item
    %a#results-tab.nav-link{'data-toggle'=>'tab', href: '#results', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.results.title')
  %li.nav-item
    %a#personal-data-tab.nav-link{'data-toggle'=>'tab', href: '#personal-data', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.personal_data.title')
  %li.nav-item
    %a#contact-tab.nav-link{'data-toggle'=>'tab', href: '#contact', role: 'tab', 'aria-controls'=>'all'}
      = t('navigation.footer.contact')
  %li.nav-item
    %a#partners-tab.nav-link{'data-toggle'=>'tab', href: '#partners', role: 'tab', 'aria-controls'=>'all'}
      = t('information.ch.partners.title')

.tab-content#information-tabs-content
  -# general
  .tab-pane.fade.show.active#general{role: 'tabpanel', 'aria-labelledby'=>'general-tab'}
    .row
      .col
        %h2 SwissSmash.ch
        %p
          = t('information.ch.general.swisssmash').html_safe
  -# calendar
  .tab-pane.fade.show#calendar{role: 'tabpanel', 'aria-labelledby'=>'calendar-tab'}
    .row
      .col
        %h2= t('information.ch.calendar.title')
        %p
          = t('information.ch.calendar.tournaments_body', link: link_to('web crawler', 'https://wikipedia.org/wiki/Web_crawler', target: '_blank')).html_safe
        %ul
          %li= link_to 'start.gg', 'https://start.gg/api/-/gg_api./public/tournaments/schedule?filter={%22upcoming%22%3Atrue%2C%22videogameIds%22%3A%221386%22%2C%22countryCode%22%3A%22CH%22}&page=1&per_page=100&returnMeta=true', target: '_blank'
          %li= link_to 'braacket.com', 'https://braacket.com/tournament/search?rows=100&country=ch&game=ssbu&status=1', target: '_blank'
          %li= link_to 'toornament.com', 'https://www.toornament.com/tournaments/?q[discipline]=supersmashbros_ultimate&q[platform]=nintendo_switch&q[type]=upcoming', target: '_blank'
    .row
      .col
        %p
          = t('information.ch.calendar.calendar_body')
        %ul
          %span.circle{style: "background: #61bf9b;"}
          %span= t('information.ch.calendar.calendar_weekly')
          %br
          %span.circle{style: "background: orchid;"}
          %span= t('information.ch.calendar.calendar_internal')
          %br
          %span.circle{style: "background: cornflowerblue;"}
          %span= t('information.ch.calendar.calendar_external')
  -# power-ranking
  .tab-pane.fade.show#power-ranking{role: 'tabpanel', 'aria-labelledby'=>'power-ranking-tab'}
    .row
      .col
        %h2= t('information.ch.power_ranking.power_ranking')
        %p= t('information.ch.power_ranking.power_ranking_body')
        %ul
          %li= t('information.ch.power_ranking.power_ranking_li_1')
          %li= t('information.ch.power_ranking.power_ranking_li_2')
          %li= t('information.ch.power_ranking.power_ranking_li_3')
          %li= t('information.ch.power_ranking.power_ranking_li_4')
          %li= t('information.ch.power_ranking.power_ranking_li_5')
          %li= t('information.ch.power_ranking.power_ranking_li_6')
  -# tournament-manager
  .tab-pane.fade.show#tournament-manager{role: 'tabpanel', 'aria-labelledby'=>'tournament-manager-tab'}
    .row
      .col
        %h2= t('information.ch.tournament_manager.tournament_organiser')
        %p= t('information.ch.tournament_manager.tournament_organiser_body').html_safe
        -# %p= t('information.ch.tournament_manager.tournament_organiser_body', link: mail_to('admin@swisssmash.ch', t('information.ch.tournament_manager.tournament_organiser_mail'), subject: t('information.ch.tournament_manager.tournament_organiser_mail_subject'), body: t('information.ch.tournament_manager.tournament_organiser_mail_body'))).html_safe
    .row
      .col
        %h2= t('information.ch.tournament_manager.bracket_tool')
        %p
          = t('information.ch.tournament_manager.bracket_tool_body', link: link_to('Challonge', 'https://challonge.com/', target: '_blank')).html_safe
    .row
      .col
        %h2= t('information.ch.tournament_manager.bracket_seeding')
        %p
          = t('information.ch.tournament_manager.bracket_seeding_body1')
          %br
          %div{style: 'margin-left: 20px;'}
            %i player_skill = points/participations + wins/(wins+losses)*100 + participations + self_assessment/5 + tournament_experience/10
          %br
          = t('information.ch.tournament_manager.bracket_seeding_body2')
  -# results
  .tab-pane.fade.show#results{role: 'tabpanel', 'aria-labelledby'=>'results-tab'}
    .row
      .col
        %h2= t('information.ch.results.title')
        %p
          = t('information.ch.results.results_body', link: link_to('SSBU CH PRs', 'https://braacket.com/league/SSBUCHPRs/tournament?rows=200', target: '_blank')).html_safe
    .row
      .col
        %h2= t('information.ch.results.ranking_system')
        %p= t('information.ch.results.ranking_system_body')
    .row
      .col
        %table.table.table-hover.table-borderless
          %thead.ranking-system-header
            %tr
              %th.text-center= t('information.ch.results.ranking_system_rank')
              %th.text-center= t('information.ch.results.ranking_system_points')
          %tbody.ranking-system-body
            %tr
              %td.text-center= 1.ordinalize
              %td.text-center 300
            %tr
              %td.text-center= 2.ordinalize
              %td.text-center 250
            %tr
              %td.text-center= 3.ordinalize
              %td.text-center 200
            %tr
              %td.text-center= 4.ordinalize
              %td.text-center 150
            %tr
              %td.text-center= 5.ordinalize+'-'+6.ordinalize
              %td.text-center 100
            %tr
              %td.text-center= 7.ordinalize+'-'+8.ordinalize
              %td.text-center 75
            %tr
              %td.text-center= 9.ordinalize+'-'+12.ordinalize
              %td.text-center 50
            %tr
              %td.text-center= 13.ordinalize+'-'+16.ordinalize
              %td.text-center 25
            %tr
              %td.text-center= 17.ordinalize+'-'+24.ordinalize
              %td.text-center 15
            %tr
              %td.text-center= 25.ordinalize+'-'+32.ordinalize
              %td.text-center 10
            %tr
              %td.text-center= '>'+32.ordinalize
              %td.text-center 5
  -# personal-data
  .tab-pane.fade.show#personal-data{role: 'tabpanel', 'aria-labelledby'=>'personal-data-tab'}
    .row
      .col
        %h2= t('information.ch.personal_data.title')
        %p= t('information.ch.personal_data.personal_data_body').html_safe
  -# contact
  .tab-pane.fade.show#contact{role: 'tabpanel', 'aria-labelledby'=>'contact-tab'}
    .row
      .col
        %h2= t('information.ch.contact.title')
        = form_tag contact_path, method: 'post', class: 'form' do
          .form-group
            = text_field_tag :name, params[:name], class: 'form-control', placeholder: t('information.ch.contact.name')
          .form-group
            = email_field_tag :email, params[:email], class: 'form-control', placeholder: t('information.ch.contact.email')
          .form-group
            = text_area_tag :body, params[:body], class: 'form-control', placeholder: t('information.ch.contact.body')
          .form-group.hidden
            = text_field_tag :url, params[:url], class: 'form-control' # hidden field_tag to trick spam bots
          .form-group
            = recaptcha_tags(site_key: ENV["RECAPTCHA_SITE_KEY_#{session['country_code'].upcase}"])
          .form-group
            = button_tag t('information.ch.contact.submit'), type: 'submit', class: 'btn btn-default'
  -# partners
  .tab-pane.fade.show#partners{role: 'tabpanel', 'aria-labelledby'=>'partners-tab'}
    = render '/partials/partners', width: '50px', height: '50px'

app/views/informations/index_de.html.haml
- set_meta_tags description: meta_tag_description('About')

.row
  .col
    %h1.page__title= t('information.de.title')

%ul#information-tabs.nav.nav-pills.nav-fill{role: 'tablist'}
  %li.nav-item
    %a#general-tab.nav-link.active{'data-toggle'=>'tab', href: '#general', role: 'tab', 'aria-controls'=>'all'}
      = t('information.de.general.title')
  %li.nav-item
    %a#calendar-tab.nav-link{'data-toggle'=>'tab', href: '#calendar', role: 'tab', 'aria-controls'=>'all'}
      = t('information.de.calendar.title')
  -# %li.nav-item
  -#   %a#power-ranking-tab.nav-link{'data-toggle'=>'tab', href: '#power-ranking', role: 'tab', 'aria-controls'=>'all'}
  -#     = t('information.de.power_ranking.title')
  %li.nav-item
    %a#tournament-manager-tab.nav-link{'data-toggle'=>'tab', href: '#tournament-manager', role: 'tab', 'aria-controls'=>'all'}
      = t('information.de.tournament_manager.title')
  %li.nav-item
    %a#results-tab.nav-link{'data-toggle'=>'tab', href: '#results', role: 'tab', 'aria-controls'=>'all'}
      = t('information.de.results.title')
  %li.nav-item
    %a#contact-tab.nav-link{'data-toggle'=>'tab', href: '#contact', role: 'tab', 'aria-controls'=>'all'}
      = t('navigation.footer.contact')
  %li.nav-item
    %a#partners-tab.nav-link{'data-toggle'=>'tab', href: '#partners', role: 'tab', 'aria-controls'=>'all'}
      = t('information.de.partners.title')

.tab-content#information-tabs-content
  -# general
  .tab-pane.fade.show.active#general{role: 'tabpanel', 'aria-labelledby'=>'general-tab'}
    .row
      .col
        %h2 GermanySmash.de
        %p
          = t('information.de.general.germanysmash', swisssmash_link: link_to('www.swisssmash.ch', 'https://www.swisssmash.ch/', target: '_blank'), Yomi: link_to('Yomi', '/players/1'), TaDavidID: link_to('TaDavidID', '/players/156')).html_safe
  -# calendar
  .tab-pane.fade.show#calendar{role: 'tabpanel', 'aria-labelledby'=>'calendar-tab'}
    .row
      .col
        %h2= t('information.de.calendar.title')
        %p
          = t('information.de.calendar.tournaments_body', link: link_to('web crawler', 'https://wikipedia.org/wiki/Web_crawler', target: '_blank')).html_safe
        %ul
          %li= link_to 'start.gg', 'https://start.gg/api/-/gg_api./public/tournaments/schedule?filter={%22upcoming%22%3Atrue%2C%22videogameIds%22%3A%221386%22%2C%22countryCode%22%3A%22DE%22}&page=1&per_page=100&returnMeta=true', target: '_blank'
          %li= link_to 'braacket.com', 'https://braacket.com/tournament/search?rows=100&country=de&game=ssbu&status=1', target: '_blank'
    .row
      .col
        %p
          = t('information.de.calendar.calendar_body')
        %ul
          %span.circle{style: "background: #61bf9b;"}
          %span= t('information.de.calendar.calendar_weekly')
          %br
          %span.circle{style: "background: orchid;"}
          %span= t('information.de.calendar.calendar_internal')
          %br
          %span.circle{style: "background: cornflowerblue;"}
          %span= t('information.de.calendar.calendar_external')
  -# tournament-manager
  .tab-pane.fade.show#tournament-manager{role: 'tabpanel', 'aria-labelledby'=>'tournament-manager-tab'}
    .row.mt-3
      .col
        %h2= t('information.de.tournament_manager.tournament_organiser')
        %p= t('information.de.tournament_manager.tournament_organiser_body').html_safe
        -# %p= t('information.de.tournament_manager.tournament_organiser_body', link: mail_to('admin@germanysmash.de', t('information.de.tournament_manager.tournament_organiser_mail'), subject: t('information.de.tournament_manager.tournament_organiser_mail_subject'), body: t('information.de.tournament_manager.tournament_organiser_mail_body'))).html_safe
    .row
      .col
        %h2= t('information.de.tournament_manager.bracket_tool')
        %p
          = t('information.de.tournament_manager.bracket_tool_body', link: link_to('Challonge', 'https://challonge.com/', target: '_blank')).html_safe
    .row
      .col
        %h2= t('information.de.tournament_manager.bracket_seeding')
        %p
          = t('information.de.tournament_manager.bracket_seeding_body1')
          %br
          %div{style: 'margin-left: 20px;'}
            %i player_skill = points/participations + wins/(wins+losses)*100 + participations + self_assessment/5 + tournament_experience/10
          %br
          = t('information.de.tournament_manager.bracket_seeding_body2')

  -# results
  .tab-pane.fade.show#results{role: 'tabpanel', 'aria-labelledby'=>'results-tab'}
    .row
      .col
        %h2= t('information.de.results.title')
        %p
          = t('information.de.results.results_body', link: link_to('SSBU DE PRs', 'https://braacket.com/league/SSBUDEPRs/tournament?rows=200', target: '_blank')).html_safe
    .row
      .col
        %h2= t('information.de.results.ranking_system')
        %p= t('information.de.results.ranking_system_body')
    .row
      .col
        %table.table.table-hover.table-borderless
          %thead.ranking-system-header
            %tr
              %th.text-center= t('information.de.results.ranking_system_rank')
              %th.text-center= t('information.de.results.ranking_system_points')
          %tbody.ranking-system-body
            %tr
              %td.text-center= 1.ordinalize
              %td.text-center 300
            %tr
              %td.text-center= 2.ordinalize
              %td.text-center 250
            %tr
              %td.text-center= 3.ordinalize
              %td.text-center 200
            %tr
              %td.text-center= 4.ordinalize
              %td.text-center 150
            %tr
              %td.text-center= 5.ordinalize+'-'+6.ordinalize
              %td.text-center 100
            %tr
              %td.text-center= 7.ordinalize+'-'+8.ordinalize
              %td.text-center 75
            %tr
              %td.text-center= 9.ordinalize+'-'+12.ordinalize
              %td.text-center 50
            %tr
              %td.text-center= 13.ordinalize+'-'+16.ordinalize
              %td.text-center 25
            %tr
              %td.text-center= 17.ordinalize+'-'+24.ordinalize
              %td.text-center 15
            %tr
              %td.text-center= 25.ordinalize+'-'+32.ordinalize
              %td.text-center 10
            %tr
              %td.text-center= '>'+32.ordinalize
              %td.text-center 5
  -# contact
  .tab-pane.fade.show#contact{role: 'tabpanel', 'aria-labelledby'=>'contact-tab'}
    .row
      .col
        %h2= t('information.de.contact.title')
        = form_tag contact_path, method: 'post', class: 'form' do
          .form-group
            = text_field_tag :name, params[:name], class: 'form-control', placeholder: t('information.de.contact.name')
          .form-group
            = email_field_tag :email, params[:email], class: 'form-control', placeholder: t('information.de.contact.email')
          .form-group
            = text_area_tag :body, params[:body], class: 'form-control', placeholder: t('information.de.contact.body')
          .form-group.hidden
            = text_field_tag :url, params[:url], class: 'form-control' # hidden field_tag to trick spam bots
          .form-group
            = recaptcha_tags(site_key: ENV["RECAPTCHA_SITE_KEY_#{session['country_code'].upcase}"])
          .form-group
            = button_tag t('information.de.contact.submit'), type: 'submit', class: 'btn btn-default'
  -# partners
  .tab-pane.fade.show#partners{role: 'tabpanel', 'aria-labelledby'=>'partners-tab'}
    = render '/partials/partners', width: '50px', height: '50px'

app/views/informations/index_fr.html.haml
- set_meta_tags description: meta_tag_description('Information')

.row
  .col
    %h1.page__title= t('information.fr.title')

%ul#information-tabs.nav.nav-pills.nav-fill{role: 'tablist'}
  %li.nav-item
    %a#general-tab.nav-link.active{'data-toggle'=>'tab', href: '#general', role: 'tab', 'aria-controls'=>'all'}
      = t('information.fr.general.title')
  %li.nav-item
    %a#calendar-tab.nav-link{'data-toggle'=>'tab', href: '#calendar', role: 'tab', 'aria-controls'=>'all'}
      = t('information.fr.calendar.title')
  %li.nav-item
    %a#power-ranking-tab.nav-link{'data-toggle'=>'tab', href: '#power-ranking', role: 'tab', 'aria-controls'=>'all'}
      = t('information.fr.power_ranking.title')
  %li.nav-item
    %a#tournament-manager-tab.nav-link{'data-toggle'=>'tab', href: '#tournament-manager', role: 'tab', 'aria-controls'=>'all'}
      = t('information.fr.tournament_manager.title')
  %li.nav-item
    %a#results-tab.nav-link{'data-toggle'=>'tab', href: '#results', role: 'tab', 'aria-controls'=>'all'}
      = t('information.fr.results.title')
  %li.nav-item
    %a#contact-tab.nav-link{'data-toggle'=>'tab', href: '#contact', role: 'tab', 'aria-controls'=>'all'}
      = t('navigation.footer.contact')
  %li.nav-item
    %a#partners-tab.nav-link{'data-toggle'=>'tab', href: '#partners', role: 'tab', 'aria-controls'=>'all'}
      = t('information.fr.partners.title')

.tab-content#information-tabs-content
  -# general
  .tab-pane.fade.show.active#general{role: 'tabpanel', 'aria-labelledby'=>'general-tab'}
    .row
      .col
        %h2 SmashUltimate.fr
        %p
          = t('information.fr.general.francesmash', swisssmash_link: link_to('www.swisssmash.ch', 'https://www.swisssmash.ch/', target: '_blank'), Yomi: link_to('Yomi', '/players/1'), telu: link_to('telu', '/players/1944')).html_safe
  -# calendar
  .tab-pane.fade.show#calendar{role: 'tabpanel', 'aria-labelledby'=>'calendar-tab'}
    .row
      .col
        %h2= t('information.fr.calendar.title')
        %p
          = t('information.fr.calendar.tournaments_body', link: link_to('web crawler', 'https://wikipedia.org/wiki/Web_crawler', target: '_blank')).html_safe
        %ul
          %li= link_to 'start.gg', 'https://start.gg/api/-/gg_api./public/tournaments/schedule?filter={%22upcoming%22%3Atrue%2C%22videogameIds%22%3A%221386%22%2C%22countryCode%22%3A%22FR%22}&page=1&per_page=100&returnMeta=true', target: '_blank'
          %li= link_to 'braacket.com', 'https://braacket.com/tournament/search?rows=100&country=fr&game=ssbu&status=1', target: '_blank'
    .row
      .col
        %p
          = t('information.fr.calendar.calendar_body')
        %ul
          %span.circle{style: "background: #61bf9b;"}
          %span= t('information.fr.calendar.calendar_weekly')
          %br
          %span.circle{style: "background: orchid;"}
          %span= t('information.fr.calendar.calendar_internal')
          %br
          %span.circle{style: "background: cornflowerblue;"}
          %span= t('information.fr.calendar.calendar_external')
  -# power-ranking
  .tab-pane.fade.show#power-ranking{role: 'tabpanel', 'aria-labelledby'=>'power-ranking-tab'}
    .row
      .col
        %h2= t('information.fr.power_ranking.power_ranking')
        %p= t('information.fr.power_ranking.power_ranking_body', link: link_to('discord', 'https://discord.com/invite/GYyBUKg', target: '_blank')).html_safe
  -# tournament-manager
  .tab-pane.fade.show#tournament-manager{role: 'tabpanel', 'aria-labelledby'=>'tournament-manager-tab'}
    .row.mt-3
      .col
        %h2= t('information.fr.tournament_manager.tournament_organiser')
        %p= t('information.fr.tournament_manager.tournament_organiser_body').html_safe
        -# %p= t('information.fr.tournament_manager.tournament_organiser_body', link: mail_to('contact@smashultimate.fr', t('information.fr.tournament_manager.tournament_organiser_mail'), subject: t('information.fr.tournament_manager.tournament_organiser_mail_subject'), body: t('information.fr.tournament_manager.tournament_organiser_mail_body'))).html_safe
    .row
      .col
        %h2= t('information.fr.tournament_manager.bracket_tool')
        %p
          = t('information.fr.tournament_manager.bracket_tool_body', link: link_to('Challonge', 'https://challonge.com/', target: '_blank')).html_safe
    .row
      .col
        %h2= t('information.fr.tournament_manager.bracket_seeding')
        %p
          = t('information.fr.tournament_manager.bracket_seeding_body1')
          %br
          %div{style: 'margin-left: 20px;'}
            %i player_skill = points/participations + wins/(wins+losses)*100 + participations + self_assessment/5 + tournament_experience/10
          %br
          = t('information.fr.tournament_manager.bracket_seeding_body2')

  -# results
  .tab-pane.fade.show#results{role: 'tabpanel', 'aria-labelledby'=>'results-tab'}
    .row
      .col
        %h2= t('information.fr.results.title')
        %p
          = t('information.fr.results.results_body', link: link_to('SSBU FR PRs', 'https://braacket.com/league/SSBUFRPRs/tournament?rows=200', target: '_blank')).html_safe
    .row
      .col
        %h2= t('information.fr.results.ranking_system')
        %p= t('information.fr.results.ranking_system_body')
    .row
      .col
        %table.table.table-hover.table-borderless
          %thead.ranking-system-header
            %tr
              %th.text-center= t('information.fr.results.ranking_system_rank')
              %th.text-center= t('information.fr.results.ranking_system_points')
          %tbody.ranking-system-body
            %tr
              %td.text-center= 1.ordinalize
              %td.text-center 300
            %tr
              %td.text-center= 2.ordinalize
              %td.text-center 250
            %tr
              %td.text-center= 3.ordinalize
              %td.text-center 200
            %tr
              %td.text-center= 4.ordinalize
              %td.text-center 150
            %tr
              %td.text-center= 5.ordinalize+'-'+6.ordinalize
              %td.text-center 100
            %tr
              %td.text-center= 7.ordinalize+'-'+8.ordinalize
              %td.text-center 75
            %tr
              %td.text-center= 9.ordinalize+'-'+12.ordinalize
              %td.text-center 50
            %tr
              %td.text-center= 13.ordinalize+'-'+16.ordinalize
              %td.text-center 25
            %tr
              %td.text-center= 17.ordinalize+'-'+24.ordinalize
              %td.text-center 15
            %tr
              %td.text-center= 25.ordinalize+'-'+32.ordinalize
              %td.text-center 10
            %tr
              %td.text-center= '>'+32.ordinalize
              %td.text-center 5
  -# contact
  .tab-pane.fade.show#contact{role: 'tabpanel', 'aria-labelledby'=>'contact-tab'}
    .row
      .col
        %h2= t('information.fr.contact.title')
        = form_tag contact_path, method: 'post', class: 'form' do
          .form-group
            = text_field_tag :name, params[:name], class: 'form-control', placeholder: t('information.fr.contact.name')
          .form-group
            = email_field_tag :email, params[:email], class: 'form-control', placeholder: t('information.fr.contact.email')
          .form-group
            = text_area_tag :body, params[:body], class: 'form-control', placeholder: t('information.fr.contact.body')
          .form-group.hidden
            = text_field_tag :url, params[:url], class: 'form-control' # hidden field_tag to trick spam bots
          .form-group
            = recaptcha_tags(site_key: ENV["RECAPTCHA_SITE_KEY_#{session['country_code'].upcase}"])
          .form-group
            = button_tag t('information.fr.contact.submit'), type: 'submit', class: 'btn btn-default'
  -# partners
  .tab-pane.fade.show#partners{role: 'tabpanel', 'aria-labelledby'=>'partners-tab'}
    = render '/partials/partners', width: '50px', height: '50px'