config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'

  Rails.application.config.default_locales.each do |locale|
    get "welcome/index_#{locale[0].to_s}" => redirect("/welcome?locale=#{locale[1]}")
  end

  get 'rules' => 'rules#index'

  get 'informations' => 'informations#index'

  get 'calendar' => 'calendar#index'
  get 'calendar_for_iframe' => 'calendar#show'

  get 'character_skins' => 'character_skins#show'

  post 'contact' => 'contact#contact'

  get 'donations' => 'donations#index'
  post 'donation' => 'donations#donation'

  get 'rankings' => 'rankings#index'

  get 'streams' => 'streams#index'

  get 'statistics' => 'statistics#index'

  get 'tos' => 'tos#index'

  get 'videos' => 'videos#index'

  # DE routes:
  get 'communities' => 'communities#index'
  get 'communities/nrw' => 'communities#nrw'
  get 'communities/hessen' => 'communities#hessen'
  get 'communities/nds' => 'communities#nds'
  get 'communities/bayern' => 'communities#bayern'
  get 'communities/berlin' => 'communities#berlin'
  get 'communities/norden' => 'communities#norden'
  get 'communities/osten' => 'communities#osten'
  get 'communities/bawu' => 'communities#bawu'

  # FR & IT routes:
  get "/communities/regions/:name" => "communities#regions"
  get "/communities/character_discords" => "communities#character_discords"
  resources :communities

  # PT routes:
  get 'locus_league' => 'locus_league#index'

  resources :teams
  post 'teams/add_player/:id' => 'teams#add_player'
  post 'teams/remove_player/:id' => 'teams#remove_player'

  resources :news
  resources :feedbacks
  # get 'administrators' => 'administrators#index'
  get 'imprint' => 'imprint#index'
  get 'privacy_policy' => 'privacy_policy#index'

  resources :tournaments
  post 'tournaments/add_player/:id' => 'tournaments#add_player'
  post 'tournaments/remove_player/:id' => 'tournaments#remove_player'
  post 'tournaments/setup/:id' => 'tournaments#setup'
  post 'tournaments/start/:id' => 'tournaments#start'
  post 'tournaments/finish/:id' => 'tournaments#finish'
  post 'tournaments/cancel/:id' => 'tournaments#cancel'
  patch 'tournaments/sort_players/:id' => 'tournaments#sort_players'
  patch 'tournaments/seed_players/:id' => 'tournaments#seed_players'

  get 'players/unregistered' => 'players#unregistered'
  post 'players/export/:id' => 'players#export'
  resources :players, except: [:new]

  resources :registrations, only: [:update]

  resources :survey_responses, only: [:create, :update]

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords' }
  resources :users, only: [:index, :update, :destroy]

  mount Thredded::Engine => '/thredded'
  get 'forum' => 'forum#index'

  namespace :shop do
    resource :shopping_cart, only: [:show, :destroy]
    get 'checkout', to: 'orders#new', as: 'checkout'
    resources :orders, only: [:index, :show, :edit, :create, :update, :destroy] # :new -> checkout
    resources :seller_orders, only: [:index, :show, :update]
    patch 'products/:id/move_down', to: 'products#move_down', as: 'product_move_down'
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :purchases, only: [:index, :create, :update, :destroy]
    namespace :stripe do
      get 'checkout', to: 'checkouts#checkout'
      get 'checkout_success', to: 'checkouts#success'
      get 'checkout_cancel', to: 'checkouts#cancel'
      post 'webhook', to: 'webhooks#webhook'
      get 'account_link', to: 'accounts#account_link'
      get 'account_return', to: 'accounts#return'
      get 'account_refresh', to: 'accounts#refresh'
    end
  end
  get 'shop', to: 'shop#index'

  root to: "welcome#index"

end

app/controllers/shop/orders_controller.rb
class Shop::OrdersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_super_admin!, only: %i[ index show destroy ]
  before_action :set_shop_order, only: %i[ show edit update destroy ]
  before_action :set_shopping_cart, only: %i[ new create ]
  before_action { @section = 'shop_orders' }

  # GET /shop/orders
  def index
    @shop_orders = Shop::Order.includes(:shopping_cart, shopping_cart: :user).order(created_at: :desc)
  end

  # GET /shop/order/1
  def show
    @shopping_cart = @shop_order.shopping_cart
  end

  # GET /shop/order/1/edit
  def edit
    @shopping_cart = @shop_order.shopping_cart
  end

  # GET /checkout
  def new
    @shop_order = Shop::Order.new
    user = @shopping_cart.user
    if user.present?
      # @shop_order.organisation = ""
      @shop_order.name = user.full_name
      # @shop_order.address = user.address
      # @shop_order.address2 = user.address2
      # @shop_order.zip_code = user.zip_code
      @shop_order.city = user.area_of_responsibility
      @shop_order.phone_number = user.mobile_number
      @shop_order.email = user.email
    end
  end

  # POST /shop/order/1
  def create
    @shop_order = Shop::Order.new(shop_order_params)
    @shop_order.shopping_cart_id = @shopping_cart.id
    @shop_order.status = 'open'
    # delete all old orders with the same shopping_cart_id as there should only be one order per shopping_cart
    Shop::Order.where(shopping_cart_id: @shopping_cart.id).destroy_all
    respond_to do |format|
      if @shopping_cart.total_price > 0 && @shop_order.save
        # stripe payment: complete order in /shop/stripe/webhook
        format.html { redirect_to shop_stripe_checkout_path(order_id: @shop_order.id) }
        format.json { render :new, status: :ok, location: @shop_order }
      else
        format.html { render :new, status: :unprocessable_content, alert: t('flash.shop_order_not_created') }
        format.json { render json: @shop_order.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /shop/order/1
  def update
    respond_to do |format|
      if @shop_order.update(shop_order_params)
        format.html { redirect_to shop_orders_path, notice: t('flash.shop_order_updated') }
        format.json { render :edit, status: :ok, location: @shop_order }
      else
        format.html { redirect_to shop_orders_path, alert: t('flash.shop_order_not_updated') }
        format.json { render json: @shop_order.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /shop/order/1
  def destroy
    respond_to do |format|
      if @shop_order.revert_checkout
        @shop_order.shopping_cart.destroy # this also destroys shop_order
        format.html { redirect_to shop_orders_path, notice: t('flash.shop_order_deleted') }
        format.json { head :no_content }
      else
        format.html { redirect_to shop_orders_path, alert: t('flash.shop_order_not_deleted') }
        format.json { render json: @shop_order.errors, status: :unprocessable_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_order
      @shop_order = Shop::Order.find(params[:id])
    end

    def set_shopping_cart
      @shopping_cart = Shop::ShoppingCart.find_latest(request.remote_ip, current_user&.id, session['session_id'])
      redirect_to shop_path unless @shopping_cart.present?
    end

    # Only allow a list of trusted parameters through.
    def shop_order_params
      params.require(:shop_order).permit(
        :organisation, :name, :address, :address2, :zip_code, :city, :email,
        :phone_number, :was_order_paid#, :payment_method
      )
    end

end

app/controllers/shop/products_controller.rb
class Shop::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_seller!, only: [:new, :create]
  before_action :set_shop_product, only: %i[ edit update destroy move_down ]
  before_action :authenticate_product_creator!, only: [:edit, :update, :destroy]
  before_action { @section = 'shop' }

  # GET /shop/products/new
  def new
    @shop_product = Shop::Product.new
  end

  # GET /shop/products/1/edit
  def edit
  end

  # POST /shop/products or /shop/products.json
  def create
    @shop_product = Shop::Product.new(shop_product_params)
    @shop_product.user_id = current_user.id
    @shop_product.country_code = session['country_code']
    respond_to do |format|
      if @shop_product.save
        ShopMailer.with(shop_product: @shop_product).new_product_email.deliver_later
        format.html { redirect_to shop_path, notice: t('flash.shop_product_created') }
        format.json { render :show, status: :created, location: @shop_product }
      else
        format.html { render :new, status: :unprocessable_content, alert: t('flash.shop_product_not_created') }
        format.json { render json: @shop_product.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /shop/products/1 or /shop/products/1.json
  def update
    respond_to do |format|
      if @shop_product.update(shop_product_params)
        format.html { redirect_to shop_path, notice: t('flash.shop_product_updated') }
        format.json { render :show, status: :ok, location: @shop_product }
      else
        format.html { render :edit, status: :unprocessable_content, alert: t('flash.shop_product_not_updated') }
        format.json { render json: @shop_product.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /shop/products/1 or /shop/products/1.json
  def destroy
    @shop_product.destroy
    respond_to do |format|
      format.html { redirect_to shop_path, notice: t('flash.shop_product_deleted') }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /shop/products/1/move_down
  def move_down
    respond_to do |format|
      if @shop_product.move_position_down(Shop::Product.where(user_id: current_user.id))
        format.html { redirect_to shop_path }#, notice: t('flash.shop_product_updated') }
        format.json { render :show, status: :ok, location: @shop_product }
      else
        format.html { redirect_to shop_path, alert: t('flash.shop_product_not_updated') }
        format.json { render json: @shop_product.errors, status: :unprocessable_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_product
      @shop_product = Shop::Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_product_params
      params.require(:shop_product).permit(
        :name, :description, :currency, :price, :shipping_national, :stock,
        :is_hidden, :image_link, :image_height, :image_width, :subtype,
        :shipping_international, :max_quantity_per_package, :variants,
        :shipping_international_eu, :description_short
      )
    end

    def authenticate_seller!
      unless current_user.present? && (current_user.admin? || current_user.has_role?("seller"))
        respond_to do |format|
          format.html { redirect_to shop_path, alert: t('flash.alert.unauthorized') }
          format.json { render json: {}, status: :unauthorized }
        end
      end
    end

    def authenticate_product_creator!
      unless current_user.present? && (@shop_product.user_id == current_user.id || current_user.super_admin?)
        respond_to do |format|
          format.html { redirect_to shop_path, alert: t('flash.alert.unauthorized') }
          format.json { render json: @shop_product.errors, status: :unauthorized }
        end
      end
    end
end

app/controllers/shop/purchases_controller.rb
class Shop::PurchasesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_shop_purchase, only: %i[ update destroy ]
  before_action { @section = 'shop' }

  # POST /shop/purchases or /shop/purchases.json
  def create
    @shopping_cart = Shop::ShoppingCart.find_or_create_latest(request.remote_ip, current_user&.id, session['session_id'], session['country_code'])
    # only update quantity if a purchase with the same product already exists
    @shop_purchase = @shopping_cart.purchases.find_by(product_id: shop_purchase_params[:product_id], variant: shop_purchase_params[:variant])
    if @shop_purchase.present?
      @shop_purchase.quantity = @shop_purchase.quantity.to_i + 1
    else
      @shop_purchase = Shop::Purchase.new(shop_purchase_params)
      @shop_purchase.shopping_cart_id = @shopping_cart.id
      @shop_purchase.quantity = 1
      @shop_purchase.stripe_account_id = @shop_purchase.product.user.stripe_account_id
    end
    was_limitted = @shop_purchase.limit_quantity
    is_same_currency = (@shopping_cart.currency.nil? || @shopping_cart.currency == @shop_purchase.currency)
    respond_to do |format|
      if (!was_limitted && is_same_currency) && @shop_purchase.save
        @shopping_cart.update(currency: @shop_purchase.currency) unless @shopping_cart.currency.present?
        format.html { redirect_to shop_path, notice: t('flash.shop_purchase_created') }
        format.json { render :show, status: :created, location: @shop_purchase }
      else
        format.html { redirect_to shop_path, alert: (is_same_currency ? t('flash.shop_purchase_not_created_limit') : t('flash.shop_purchase_not_created_currency', currency: @shopping_cart.currency_text)) }
        format.json { render json: @shop_purchase.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /shop/purchases/1 or /shop/purchases/1.json
  def update
    @shop_purchase.assign_attributes(shop_purchase_params)
    was_limitted = @shop_purchase.limit_quantity
    respond_to do |format|
      if @shop_purchase.quantity.to_i >= 0 && @shop_purchase.save
        format.html {
          if was_limitted
            redirect_to shop_shopping_cart_path, flash: {warn: t('flash.shop_purchase_limitted')}
          else
            redirect_to shop_shopping_cart_path, notice: t('flash.shop_purchase_updated')
          end
        }
        format.json { render :show, status: :ok, location: @shop_purchase }
      else
        format.html { redirect_to shop_shopping_cart_path, alert: t('flash.shop_purchase_not_updated') }
        format.json { render json: @shop_purchase.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /shop/purchases/1 or /shop/purchases/1.json
  def destroy
    shopping_cart = @shop_purchase.shopping_cart
    @shop_purchase.destroy
    respond_to do |format|
      format.html {
        # redirect to the shop if no purchases are left
        if shopping_cart.purchases.any?
          redirect_to shop_shopping_cart_path, notice: t('flash.shop_purchase_deleted')
        else
          shopping_cart.destroy
          redirect_to shop_path, notice: t('flash.shop_purchase_deleted')
        end
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_purchase
      @shop_purchase = Shop::Purchase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_purchase_params
      params.require(:shop_purchase).permit(:quantity, :product_id, :variant)
    end

end

app/controllers/shop/seller_orders_controller.rb
class Shop::SellerOrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_seller!
  before_action :set_shop_seller_order, only: %i[ show update ]
  before_action :authenticate_seller_order_owner!, only: %i[ show update ]
  before_action { @section = 'shop_seller_orders' }

  # GET /shop/seller_orders
  def index
    # blup: eventuell nur .paid seller_orders anzeigen?
    @shop_seller_orders = current_user.seller_orders.includes(:order).order(created_at: :desc)
  end

  # GET /shop/seller_order/1
  def show
    @shop_order = @shop_seller_order.order
  end

  # PATCH/PUT /shop/seller_order/1
  def update
    respond_to do |format|
      if @shop_seller_order.update(shop_seller_order_params)
        format.html { redirect_to shop_seller_orders_path, notice: t('flash.shop_order_updated') }
        format.json { render json: {}, status: :ok, location: @shop_seller_order }
      else
        format.html { redirect_to shop_seller_orders_path, alert: t('flash.shop_order_not_updated') }
        format.json { render json: @shop_seller_order.errors, status: :unprocessable_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_seller_order
      @shop_seller_order = Shop::SellerOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_seller_order_params
      params.require(:shop_seller_order).permit(:was_order_sent)
    end

    def authenticate_seller!
      unless current_user.present? && (current_user.admin? || current_user.has_role?("seller"))
        respond_to do |format|
          format.html { redirect_to shop_path, alert: t('flash.alert.unauthorized') }
          format.json { render json: {}, status: :unauthorized }
        end
      end
    end

    def authenticate_seller_order_owner!
      unless current_user.present? && (@shop_seller_order.user_id == current_user.id || current_user.super_admin?)
        respond_to do |format|
          format.html { redirect_to shop_path, alert: t('flash.alert.unauthorized') }
          format.json { render json: @shop_seller_order.errors, status: :unauthorized }
        end
      end
    end

end

app/views/shop/products/_form.html.haml
= form_for @shop_product, role: 'form', class:'form' do |f|

  - if @shop_product.errors.any?
    #error_explanation
      -# %h2= pluralize(@shop_product.errors.count, "error") + ' ' + t('shop.product.prohibited')
      %ul
        - @shop_product.errors.full_messages.each do |message|
          %li= message

  .field.form-group
    = f.label :subtype, t('activerecord.attributes.shop_product.subtype')
    .form-check
      = radio_button('shop_product', 'subtype', 'service', checked: (@shop_product.subtype == 'service' || @shop_product.new_record?), class: 'form-check-input', style: 'margin-right: 10px;', onclick: "document.getElementById('subtype-target').style.display = 'none';")
      %label.form-check-label{for: "shop_product_subtype_service"}= t('shop.products.subtypes.service')
    .form-check
      = radio_button('shop_product', 'subtype', 'digital', checked: (@shop_product.subtype == 'digital'), class: 'form-check-input', style: 'margin-right: 10px;', onclick: "document.getElementById('subtype-target').style.display = 'none';")
      %label.form-check-label{for: "shop_product_subtype_digital"}= t('shop.products.subtypes.digital')
    .form-check
      = radio_button('shop_product', 'subtype', 'physical', checked: (@shop_product.subtype == 'physical'), class: 'form-check-input', style: 'margin-right: 10px;', onclick: "document.getElementById('subtype-target').style.display = 'block';")
      %label.form-check-label{for: "shop_product_subtype_physical"}= t('shop.products.subtypes.physical')

  .field.form-group
    = f.label :image_link, t('teams.image_link')
    %em= t('teams.image_owner')
    = f.text_field :image_link, placeholder: "https://i.imgur.com/<my-image>.jpg", class: 'form-control'
  -# .row
  -#   .col.field.form-group
  -#     = f.label :image_height, t('teams.image_height')
  -#     = f.text_field :image_height, placeholder: t('teams.image_height_placeholder'), class: 'form-control'
  -#   .col.field.form-group
  -#     = f.label :image_width, t('teams.image_width')
  -#     = f.text_field :image_width, placeholder: t('teams.image_height_placeholder'), class: 'form-control'
  .field.form-group
    = f.label :name, t('activerecord.attributes.shop_product.name')
    = f.text_field :name, class: 'form-control'
  .field.form-group
    = f.label :description_short, t('activerecord.attributes.shop_product.description_short')
    = f.text_field :description_short, class: 'form-control'
  .field.form-group
    = f.label :description, t('activerecord.attributes.shop_product.description')
    = f.text_area :description, class: 'form-control'
  .field.form-group
    = f.label :currency, t('activerecord.attributes.shop_product.currency')
    = f.select :currency, options_for_select(currency_for_select, @shop_product.currency || Domain.iso_currency_from(session[:country_code])), {include_blank: true}, class: 'form-control'
    - if session[:country_code] == 'is'
      %em
        = '( Unfortunately, Stripe does not seem to support the Icelandic Krona as an alternative currency ->'
        = link_to 'Doc', 'https://docs.stripe.com/payouts/alternative-currencies', target: '_blank'
        = ')'
  .field.form-group
    = f.label :price, t('activerecord.attributes.shop_product.price')
    = f.number_field :price, class: 'form-control', value: @shop_product.price || 1, step: 0.1, min: 1
  .field.form-group
    = f.label :variants, t('activerecord.attributes.shop_product.variants')
    %em= t('shop.products.variants_info')
    = f.text_field :variants, class: 'form-control'
  #subtype-target{class: @shop_product.subtype != 'physical' ? 'hidden' : ''}
    .field.form-group
      = f.label :shipping_national, t('activerecord.attributes.shop_product.shipping_national')
      .row
        .col
          = f.number_field :shipping_national, class: 'form-control', value: @shop_product.shipping_national || 0, step: 0.1, min: 0
          %em= t('shop.products.shipping_types.national')
        .col
          = f.number_field :shipping_international_eu, class: 'form-control', value: @shop_product.shipping_international_eu || 0, step: 0.1, min: 0
          %em= t('shop.products.shipping_types.international_eu')
        .col
          = f.number_field :shipping_international, class: 'form-control', value: @shop_product.shipping_international || 0, step: 0.1, min: 0
          %em= t('shop.products.shipping_types.international')
    .field.form-group
      = f.label :max_quantity_per_package, t('activerecord.attributes.shop_product.max_quantity_per_package')
      = f.number_field :max_quantity_per_package, class: 'form-control', value: @shop_product.max_quantity_per_package || 1, step: 1, min: 1
    .field.form-group
      = f.label :stock, t('activerecord.attributes.shop_product.stock')
      = f.number_field :stock, class: 'form-control', value: @shop_product.stock || 0, step: 1, min: 0
  .field.form-group
    %label.checkbox
      %input{autocomplete: "off", name: "shop_product[is_hidden]", type: "hidden", value: "0"}
      %input{type: "checkbox", id: "shop_product_is_hidden", name: "shop_product[is_hidden]", value: "1", checked: @shop_product.is_hidden}
      %span= t('activerecord.attributes.shop_product.is_hidden')

  .row
    .col
      %p.mb-0
        = t('shop.products.terms_of_use.title')
      %ul{style: 'font-size: 10px;'}
        %li= t('shop.products.terms_of_use.li1')
        %li= t('shop.products.terms_of_use.li2')
        %li= t('shop.products.terms_of_use.li3')
        %li= t('shop.products.terms_of_use.li4')
        %li= t('shop.products.terms_of_use.li5')
        %li= t('shop.products.terms_of_use.li6')
        %li= t('shop.products.terms_of_use.li7')
        %li= t('shop.products.terms_of_use.li8')
        %li= t('shop.products.terms_of_use.li9')
        %li= t('shop.products.terms_of_use.li10', link: link_to("https://stripe.com/de-ch/pricing", "https://stripe.com/de-ch/pricing", target: "_blank")).html_safe
        %li= t('shop.products.terms_of_use.li11')
        %li= t('shop.products.terms_of_use.li12', date: "23.07.2024")

  .actions.form-group
    = f.submit class:'btn btn-block btn-cyan btn-with-icon'

-# back button
.row
  .col.text-center
    = link_to shop_path do
      %button.btn.btn-default.btn-with-icon
        %i.material-icons{style: 'font-size: 20px;'} keyboard_backspace
        %span= t('back')

app/views/shop/products/edit.html.haml
.row
  .col
    %h1.page__title= t('shop.products.edit')

= render 'shop/beta_header' #blup: beta

.row.form
  .col
    = render 'form'

-# TODO -> add was_deleted to shop_products
- if current_user.present? && current_user.is_super_admin?
  .hidden.admin-list-actions.text-center{style: 'position: absolute; top: 10px; right: 10px;'}
    .admin-list-actions__link
      = button_to shop_product_path(@shop_product), method: :delete, form: { data: { turbo_method: :delete, turbo_confirm: t('confirm') } }, class: 'btn btn-sstm btn-square' do
        %i.material-icons.admin-actions__link__icon= 'delete'

app/views/shop/products/new.html.haml
.row
  .col
    %h1.page__title= t('shop.products.new')

= render 'shop/beta_header' #blup: beta

.row.form
  .col
    = render 'form'